version: 2
project_name: tflint-ruleset-tmn
env:
  - CGO_ENABLED=0
builds:
  - binary: tflint-ruleset-tmn
    targets:
      - darwin_arm64
      - linux_amd64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
  extra_files:
    - glob: ./dist/raw/*
release:
  github:
